development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:0e64806b4e955c8ccd27ef29ffd7c996@spinyfin.redistogo.com:10063/
  channel_prefix: virtual_canvas_backend_api_production
